### ISSUE TITLE
JavaFixture should not overwrite values set in constructor

### ISSUE THREAD

**Issue by akutschera** [Nylle/JavaFixture#12]
When I create a JavaFixture object for a class that sets values in the constructor, e.g.
```
public class TestObjectWithConstructorAssignment {

    int value;
    int computed;

    public TestObjectWithConstructorAssignment(int value ) {
        this.value = value;
        computed = value;
    }

}
```
I expect that ```value``` and ```computed``` are the same after JavaFixture.create is done, but they are different random values which breaks some of my tests

**Comment by Nylle** [comment]
The reason for this behaviour is that when `TestObjectWithConstructorAssignment` is created, the constructor will not be called; JavaFixture doesn't know about constrcuctors - instead it tries to create an instance using the default-constructor ("magically" even if it is not present), injecting the values later on.

If you want to create an instance of `TestObjectWithConstructorAssignment` thorugh constructor, why use JavaFixture in the first place and not just call the constructor directly?

**Comment by akutschera** [comment]
Agreed. The only reason was to have random values in my constructor (and the fact that JavaFixture could - in the past - not create objects that had fields of type class somewhere deep in the tree.
We could close this issue and re-open it when there is a new use case for this

**Comment by Nylle** [comment]
I think, I understand better now. You want a way, that JavaFixture can be called for a specified constructor and then automagically generate the arguments for you? That sounds like an interesting little piece of syntactic sugar. I'd say we keep this issue open then.

In the mean time, using `@TestWithFixture`, you can generate the constructor-arguments right away and just pass them to the constructor.

**Comment by Nylle** [comment]
I played around with functional interfaces, but the sad truth is, parameter types get lost due to the infamous type erasure. I haven't found a way to reflect the types from within the interface.
```java
(String x, Integer y, Boolean z) -> new MyClass(x, y, z)
``` 
Instead of `String.class` for `x`, I just get `A` (as in `NFunction<A,B,C,R>` with `A`, `B`, `C` as parameters and `R` as return type).

The only way I can think of right now, is to provide a method that lets the user decide which constructor to use, by providing the index:
```java
fixture().create(SpecimenType.fromClass(MyObject.class)).createWithConstructor(1);
```
This would then try and get the second constructor (index = 1) from the class and fill it with fixtures.
However, there would be no auto-completion support from your IDE and the hardcoded index would not be refactoring-safe. That means, if you chose to move around your constructors or change their signatures, the compiler would not detect that, but the test might suddenly behave differently.

I think, this is an interesting challenge and I already learned a lot about Java's functional interfaces by playing around, but right now I ran out of ideas. If you have further ideas, please post them - or play around on your own.

**Comment by Nylle** [comment]
Another option would be to have JavaFixture randomly select one of the existing public constructors (if there are any) instead of force-creating the object through the default-constructor and filling the fields.
