### ISSUE TITLE
Cannot create Fixture of Throwable

### ISSUE THREAD

**Issue by akutschera** [Nylle/JavaFixture#15]
The simple example:
```new JavaFixture().create(Throwable.class)```
This should give me a random Throwable object. Instead I get 
```com.github.nylle.javafixture.SpecimenException: Unsupported type for generic creation: class java.lang.Class```
This becomes a problem when I have a DTO that contains a member of type Throwable.
Building/creating the DTO without the Throwable field also fails.

Maybe a random Exception or something would be enough in this case

**Comment by Nylle** [comment]
A random exception would of course fix this issue. It would be however just treating the symptoms. As I see it, you discovered two bugs:
(1) There is a problem with creating a random object from an interface (I'd expect that JavaFixture would be able to create an object from any interface I ever provide, including `Throwable` but also any other possible interface).
(2) The `without()`-extension is a fake. I have to admit, that I simply faked the bahaviour by creating the full object-tree first and then overwriting the omitted fields with `null`. It was built this way, because in the first version random-beans was used as the unerdyling library. Now that JavaFixture proviudes its own means of object-tree generation we could consider re-implementing the `without`-feature in a proper way.

**Comment by akutschera** [comment]
Well, maybe JavaFixture is actually doing **too much**.
In case of a Throwable (or probably any other "non data class") it is enough to just create an instance, and **then** fill any explicitly specified fields.
Or just fill the fields that the constructor does not set.

Of course, the "without"-extension should lead to the field not being created in the first place (which would help to delay the decision of how to solve problem 1 :-)

**Comment by Nylle** [comment]
I think I misunderstood the issue. I assumed `Throwable` to be an interface that's wrongly proxied, but it's a class actually. The existing code only supports parametrized types implementing `Collection` or `Map` whereas `Throwable` requires the parametrized type `Class<?>`.
I think, a viable solution to fix this ASAP is to include a `GenericObjectSpecimen` supporting `Class<?>` as well. I still welcome and encourage further discussion whether _JavaFixture is actually doing **too much**_.
I created a second [issue](https://github.com/Nylle/JavaFixture/issues/16) for the broken `without()`-feature.

**Comment by Nylle** [comment]
Fixed in version 1.2.3
