### ISSUE TITLE
Make fixture creation more robust by using fallback strategies

### ISSUE THREAD

**Issue by akutschera** [Nylle/JavaFixture#63]
When I specify that I want to use a random constructor, I would expect JavaFixture to use it for all objects it creates.
The following test fails
```
       @Test
        void constructorShouldBeRecursive() {
            Fixture fixture = new Fixture(configuration);

            var result = fixture.construct(Demo.class);

            assertThat(result.getFoo().getPrivateField()).isNull();
        }

        class SubClass {
            private final String privateField = null;

            public SubClass() {}

            public String getPrivateField() {
                return privateField;
            }
        }
        class Demo {
            private final SubClass foo;

            public Demo(SubClass foo) {
                this.foo = foo;
            }

            public SubClass getFoo() {
                return foo;
            }
        }
```
It fails because the "privateField" is set to a value.

**Comment by Nylle** [comment]
This behaviour is actually exactly as intended: `construct()` will just choose a random constructor and supply the arguments as normal fixtures. Those arguments will be created using reflection. That's why `getPrivateField()` is not `null`.

I'd say it's not a bug, but you obviously expected a different behaviour; may I ask which problem you're trying to solve? (Maybe there's a feature here?)

**Comment by akutschera** [comment]
Maybe.
The use case is records with Java 17. Using JavaFixture 2.7.0 you can ```construct()``` a record when it is the top-level object, you cannot when it is a member field. Using ```create()``` fails with a record.
Of course, we could alternatively **always** build a record with ```construct()``` and do that transparently. That is something we can defer until JavaFixture supports Java 17.

**Comment by jan-kockrow-idealo** [comment]
That is a very good point! The whole `construct()` feature was actually meant to solve exactly those issues: when Fixture is unable to create an object with on-board means, calling a constructor should _always_ work.
I'd suggest, we fix that, to enable Fixture to create records prior to supporting Java 17.
And in order to support 17 down the road we can think of how to support records natively, either as you suggested or with a separate specimen (or maybe it's both?).

**Comment by Nylle** [comment]
That is a very good point! The whole `construct()` feature was actually meant to solve exactly those issues: when Fixture is unable to create an object with on-board means, calling a constructor should _always_ work.
I'd suggest, we fix that, to enable Fixture to create records prior to supporting Java 17.
And in order to support 17 down the road we can think of how to support records natively, either as you suggested or with a separate specimen (or maybe it's both?).

**Comment by akutschera** [comment]
After looking at use cases I propose the following:
We ```create``` an object using a three step approach.
Step 1:
We use a public empty constructor or objenesis to create an instance and then set all fields using reflection.
If that works we return the object. If it fails we go to 
Step 2:
We use any public constructor (and create fixtures for all arguments). We will *not* set any additional fields.
If that works we return the object. If it fails we go to
Step 3:
We use any factory method that the class provides (and create fixtures for all factory-method arguments).
If that works we return the object. It it fails we give up.

The advantage of this is we can create records (even with the Java 11 version of the library). We can also fixture objects of standard Java classes that won't let us set fields via reflection anymore.
Since > 90% of use cases of JavaFixture involve Strings, Numbers, Temporals and Collections we will usually succeed in step one.
The slight change this will bring is that JavaFixture will return an ```Optional.empty()``` in 1 of 3 cases. Still, that is a valid random value.

**Comment by Nylle** [comment]
The generation of an object-tree per constructor was originally used as a workaround to create java17-records. I think, that problem has already been solved, right?
If we decide to keep that functionality for similar cases, it would make sense to make `construct()` work in the way you expected, so that nested fixtures are constructed as well?
