### ISSUE TITLE
BigInteger may cause hanging tests in jdk17

### ISSUE THREAD

**Issue by jk-idealo** [Nylle/JavaFixture#78]
The following test will **sometimes** hang and run forever without errors or exceptions in **java 17**:
```java
    @Test
    void xxx() {
        var result = fixture().create(BigInteger.class);

        assertThat(result).isInstanceOf(BigInteger.class);
    }
```

**Comment by akutschera** [comment]
That's an interesting one.
Because of JDK17 we cannot use reflection.
Then we use a fallback that tries to use a random constructor. These will fail in most cases (we may get lucky if we randomly choose ```new Random(int numBits, Random rnd)``` **and** randomly call it with a positive numBits value).
If the constructor fails we fallback to the factory methods. There we have two:

- ```valueOf(long val)``` which will always succeed and
- ```probablePrime(int bitLength, Random rnd)``` which will succeed when bitLength is not negative
When bitLength is a large number (e.g. 5_000) the probablePrime call takes a long time to finish (>7s on my machine, compared to 300ms for 1_000 bits).

I suggest that we add BigInteger to the special specimens that need extra knowledge for fixturing, like URL.

**Comment by akutschera** [comment]
Creating a BigInteger with the maximum number of possible bits takes quite long (>1000ms) each time. Therefore I propose to limit a fixtured BigInteger to max. 1024 bit. If someone needs more, we can still add a configuration parameter.
